Repository okTurtles/group-income, pull requests merged in 2020-09, with the labels that each got.

#922 Close #844: Implement updates to the User Settings page
  frontend/assets/style/_base.scss
  frontend/assets/style/_transitions.scss
  frontend/assets/style/_typography.scss
  frontend/assets/style/_variables.scss
  frontend/assets/style/components/_forms.scss
  frontend/assets/style/components/_steps.scss
  frontend/model/state.js
  frontend/utils/lazyLoadedView.js
  frontend/views/components/AppStyles.vue
  frontend/views/components/Slider.vue
  frontend/views/components/graphs/Bars.vue
  frontend/views/components/graphs/SupportHistory.vue
  frontend/views/components/menu/MenuContent.vue
  frontend/views/components/modal/ModalClose.vue
  frontend/views/components/modal/ModalTemplate.vue
  frontend/views/components/tabs/TabItems.vue
  frontend/views/components/tabs/TabWrapper.vue
  frontend/views/containers/navigation/Activity.vue
  frontend/views/containers/navigation/Profile.vue
  frontend/views/containers/user-settings/Appearence.vue
  frontend/views/containers/user-settings/FontSize.vue
  frontend/views/containers/user-settings/Placeholder.vue
  frontend/views/containers/user-settings/Theme.vue
  frontend/views/containers/user-settings/UserSettingsModal.vue
  frontend/views/containers/user-settings/settings.js
Labels: App:Frontend

#976 Restore flags to map Docker ports.
  scripts/docker.sh
Labels: App:Backend, App:Frontend, Kind:Bug, Level:Starter, Note:Tooling

#950 #865 Improve mincome inputs ux
  frontend/views/components/group-creation-steps/GroupMincome.vue
  frontend/views/containers/contributions/IncomeDetails.vue
  frontend/views/containers/group-settings/GroupCreationModal.vue
  frontend/views/containers/proposals/Mincome.vue
  frontend/views/utils/currencies.js
Labels: Priority:High

#946 #935 Using modals - queries instead of props
  frontend/controller/actions/group.js
  frontend/controller/router.js
  frontend/model/contracts/group.js
  frontend/utils/events.js
  frontend/utils/lazyLoadedView.js
  frontend/views/components/modal/Modal.vue
  frontend/views/containers/design-system/DSModalFullscreen.vue
  frontend/views/containers/design-system/DSModalQuery.vue
  frontend/views/containers/group-settings/GroupRulesSettings.vue
  frontend/views/containers/navigation/CypressBypassUI.vue
  frontend/views/containers/payments/PaymentDetail.vue
  frontend/views/containers/payments/PaymentRowReceived.vue
  frontend/views/containers/payments/PaymentRowSent.vue
  frontend/views/containers/proposals/ChangeVotingRules.vue
  frontend/views/containers/proposals/RemoveMember.vue
  frontend/views/containers/user-settings/AppLogs.vue
  frontend/views/containers/user-settings/UserSettingsModal.vue
  frontend/views/pages/DesignSystem.vue
Labels: Priority:High

#923 #538 better avatar placeholders
  frontend/assets/images/default-avatar.png
  frontend/assets/images/default-group-avatar.png
  frontend/assets/images/group-avatar-default.png
  frontend/assets/images/user-avatar-default.png
  frontend/assets/images/user-avatar-pending.png
  frontend/controller/actions/group.js
  frontend/controller/actions/identity.js
  frontend/utils/blockies.js
  frontend/utils/image.js
  frontend/views/components/AvatarGenerator.vue
  frontend/views/components/AvatarUpload.vue
  frontend/views/components/group-creation-steps/GroupName.vue
  frontend/views/containers/access/SignupForm.vue
  frontend/views/containers/chatroom/fakeStore.js
  frontend/views/containers/dashboard/GroupMembers.vue
  frontend/views/containers/group-settings/GroupCreationModal.vue
  frontend/views/pages/Mailbox.vue
  test/backend.test.js
Labels: Priority:High

#951 #763 Payments - improve search, tabs and tests
  frontend/model/state.js
  frontend/views/components/Search.vue
  frontend/views/containers/payments/MonthOverview.vue
  frontend/views/containers/payments/PaymentDetail.vue
  frontend/views/containers/payments/PaymentsPagination.vue
  frontend/views/pages/Payments.vue
  test/cypress/integration/group-paying.spec.js
Labels: Priority:High

#948 Improve the UI stack of each page in the app. Close #562
  frontend/assets/style/components/_loading.scss
  frontend/assets/style/main.scss
  frontend/controller/router.js
  frontend/main.js
  frontend/model/state.js
  frontend/utils/lazyLoadedView.js
  frontend/views/components/modal/ModalMixins.js
  frontend/views/containers/loading-error/ErrorModal.vue
  frontend/views/containers/loading-error/ErrorPage.vue
  frontend/views/containers/loading-error/LoadingBaseModal.vue
  frontend/views/containers/loading-error/LoadingModal.vue
  frontend/views/containers/loading-error/LoadingPage.vue
  shared/declarations.js
Labels: App:Frontend, Priority:High
